#' Temporal microbiome composition data
#'
#' A subset of the data generated by Katherine Xue et al. detailing longitudinal
#' composition of the human gut microbiome for three subjects who experience an
#' antiobitic perturbation between days 29 and 34. We include only the subjects
#' XAA, XBA, and XCA.
#'
#' @format ## `xue_microbiome_sample`
#' A data frame with 75 rows and 1,348 columns:
#' \describe{
#'   \item{subject}{Subject ID: XAA, XBA, or XCA
#'   \item{timepoint}{Time (days) of sample collection}
#'   \item{...}{Species names}
#'   ...
#' }
"xue_microbiome_sample"
